/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlycoffee;

import DAO.NguyenLieuDAO;
import DBConnect.DBConnect;
import Model.NguyenLieu;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class FormNguyenLieu extends javax.swing.JFrame {

    DefaultTableModel tblModelNL;

    /**
     * Creates new form FormNguyenLieu
     */
    public FormNguyenLieu() {
        initComponents();
        setLocationRelativeTo(null);
        initTable();
        loadData();
        loadCombobox();
        setTitle("Nguyên Liệu");

    }

    private void lamTrong() {
        cbxMaNCC.setSelectedItem(null);
        cbxMaMon.setSelectedItem(null);
        txtMaNL.setText("");
        txtTenNL.setText("");
        txtSL.setText("");
        txtDVT.setText("");
    }

    public boolean blockButton(boolean x) {
        if (x == true) {
            btnSuaNL.setEnabled(false);
            btnXoaNL.setEnabled(false);
            btnThemNL.setEnabled(true);
            btnThoatNL.setEnabled(true);
            return true;
        } else {
            btnSuaNL.setEnabled(true);
            btnXoaNL.setEnabled(true);
            btnThemNL.setEnabled(false);
            btnThoatNL.setEnabled(false);
            return false;
        }
    }

    public void loadCombobox() {
        try {
            DBConnect a = new DBConnect();
            Connection con = a.getConnection();
            PreparedStatement psMaMon = con.prepareStatement("Select MaMon from DoUong group by MaMon");
            PreparedStatement psMaNCC = con.prepareStatement("Select MaNCC from NhaCungCap group by MaNCC");
            ResultSet rsMaMon = psMaMon.executeQuery();
            ResultSet rsMaNCC = psMaNCC.executeQuery();
            while (rsMaMon.next()) {
                cbxMaMon.addItem(rsMaMon.getString("MaMon"));
            }
            while (rsMaNCC.next()) {
                cbxMaNCC.addItem(rsMaNCC.getString("MaNCC"));
            }
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }

    private void initTable() {
        tblModelNL = new DefaultTableModel();
        tblModelNL.setColumnIdentifiers(new String[]{"MaNCC", "MaMon", "MaNL", "TenNL", "SoLuong", "DVT", "Tien"});
        tblNguyenLieu.setModel(tblModelNL);
    }

    public void loadData() {
        try {
            DBConnect a = new DBConnect();
            Connection con = a.getConnection();
            String sql = "Select * from NguyenLieu";
            PreparedStatement pstmt = con.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            tblModelNL.setRowCount(0);
            while (rs.next()) {
                String[] row = new String[]{
                    rs.getString("MaNCC"), rs.getString("MaMon"), rs.getString("MaNL"), rs.getString("TenNL"), rs.getString("SoLuong"), rs.getString("DVT"), rs.getString("Tien")
                };
                tblModelNL.addRow(row);
            }
            tblModelNL.fireTableDataChanged();
            rs.close();
            pstmt.close();
            con.close();
            blockButton(true);
            txtMaNL.setEnabled(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaNL = new javax.swing.JTextField();
        txtTenNL = new javax.swing.JTextField();
        txtSL = new javax.swing.JTextField();
        txtDVT = new javax.swing.JTextField();
        cbxMaMon = new javax.swing.JComboBox<>();
        cbxMaNCC = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNguyenLieu = new javax.swing.JTable();
        btnThemNL = new javax.swing.JButton();
        btnSuaNL = new javax.swing.JButton();
        btnXoaNL = new javax.swing.JButton();
        btnThoatNL = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtGia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 23)); // NOI18N
        jLabel1.setText("QUẢN LÝ NGUYÊN LIỆU");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, 50));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel2.setText("Mã Nguyên Liệu");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel3.setText("Mã Món");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel4.setText("Mã Nhà Cung Cấp");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel5.setText("Tên Nguyên Liệu");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel6.setText("Đơn Vị Tính");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, 23));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel7.setText("Số Lượng");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, 30));
        getContentPane().add(txtMaNL, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 130, 30));
        getContentPane().add(txtTenNL, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 130, 30));
        getContentPane().add(txtSL, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 130, 30));
        getContentPane().add(txtDVT, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 128, 30));
        getContentPane().add(cbxMaMon, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 128, 30));
        getContentPane().add(cbxMaNCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 130, 30));

        tblNguyenLieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Nhà Cung Cấp", "Mã Món", "Mã Nguyên Liệu", "Tên Nguyên Liệu", "Số Lượng", "ĐVT"
            }
        ));
        tblNguyenLieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNguyenLieuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNguyenLieu);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 625, 206));

        btnThemNL.setBackground(new java.awt.Color(255, 255, 204));
        btnThemNL.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnThemNL.setText("Thêm");
        btnThemNL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNLActionPerformed(evt);
            }
        });
        getContentPane().add(btnThemNL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 80, 30));

        btnSuaNL.setBackground(new java.awt.Color(255, 255, 204));
        btnSuaNL.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnSuaNL.setText("Sửa");
        btnSuaNL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNLActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuaNL, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 80, 30));

        btnXoaNL.setBackground(new java.awt.Color(255, 255, 204));
        btnXoaNL.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnXoaNL.setText("Xoá");
        btnXoaNL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNLActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoaNL, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 80, 30));

        btnThoatNL.setBackground(new java.awt.Color(255, 255, 204));
        btnThoatNL.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnThoatNL.setText("Thoát");
        btnThoatNL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatNLActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoatNL, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 70, 30));

        btnLamMoi.setBackground(new java.awt.Color(255, 255, 204));
        btnLamMoi.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        getContentPane().add(btnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 100, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jButton1.setText("QL Nhà CC");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, -1, 30));
        getContentPane().add(txtGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 130, 30));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel8.setText("Giá");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/backround.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 0, 810, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblNguyenLieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNguyenLieuMouseClicked
        int row = tblNguyenLieu.getSelectedRow();
        txtMaNL.setEnabled(false);
        blockButton(false);
        if (row >= 0) {
            cbxMaNCC.setSelectedItem(tblNguyenLieu.getModel().getValueAt(row, 0) + "");
            cbxMaMon.setSelectedItem(tblNguyenLieu.getModel().getValueAt(row, 1) + "");
            txtMaNL.setText(tblNguyenLieu.getValueAt(row, 2) + "");
            txtTenNL.setText(tblNguyenLieu.getValueAt(row, 3) + "");
            txtSL.setText(tblNguyenLieu.getValueAt(row, 4) + "");
            txtDVT.setText(tblNguyenLieu.getValueAt(row, 5) + "");
            txtGia.setText(tblNguyenLieu.getValueAt(row, 6) + "");
        }
    }//GEN-LAST:event_tblNguyenLieuMouseClicked

    private void btnThemNLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNLActionPerformed
        StringBuffer sb = new StringBuffer();
        if (txtMaNL.getText().equals("") || txtTenNL.getText().equals("") || txtSL.getText().equals("") || txtDVT.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập đủ thông tin!", "Thông báo!", JOptionPane.ERROR_MESSAGE);
            //Bẫy lỗi nhập thiếu dữ liệu.
        } else {
            if (txtMaNL.getText().trim().length() > 6) {
                JOptionPane.showMessageDialog(this, "Mã nguyên liệu không vượt quá 6 ký tự! ");
                txtMaNL.grabFocus();
            }
            if (sb.length() > 0) {    //Nếu if trên đúng thì sẽ thêm vào sb 1 đoạn string
                //Kiểm tra độ dài chuỗi này nếu lớn hơn  0 tức là có thông báo
                JOptionPane.showMessageDialog(this, sb);
                return;
            } else {
                try {
                    NguyenLieu nl = new NguyenLieu();
                    nl.setMaNCC(cbxMaNCC.getSelectedItem().toString());
                    nl.setMaMon(cbxMaMon.getSelectedItem().toString());
                    nl.setMaNL(txtMaNL.getText());
                    nl.setTenNL(txtTenNL.getText());
                    nl.setSoLuong(Integer.parseInt(txtSL.getText()));
                    nl.setDVT(txtDVT.getText());
                    nl.setTien(Integer.parseInt(txtGia.getText()));
                    NguyenLieuDAO nlDao = new NguyenLieuDAO();
                    nlDao.insert(nl);
                    JOptionPane.showMessageDialog(this, "Thêm nguyên liệu thành công!");
                    lamTrong();
                    loadData();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Mã nguyên liệu bị trùng lặp!");
                    ex.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_btnThemNLActionPerformed

    private void btnSuaNLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNLActionPerformed
        StringBuffer sb = new StringBuffer();
        if (txtMaNL.getText().equals("") || txtTenNL.getText().equals("") || txtSL.getText().equals("") || txtDVT.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập đủ thông tin!", "Thông báo!", JOptionPane.ERROR_MESSAGE);
            //Bẫy lỗi nhập thiếu dữ liệu.
        }
        //Ngược lại thêm bẫy lỗi nếu trùng khoá chính.
        if (sb.length() > 0) {    //Nếu if trên đúng thì sẽ thêm vào sb 1 đoạn string
            //Kiểm tra độ dài chuỗi này nếu lớn hơn  0 tức là có thông báo
            JOptionPane.showMessageDialog(this, sb);
            return;
        }
        try {
            NguyenLieu nl = new NguyenLieu();
            nl.setMaNCC(cbxMaNCC.getSelectedItem().toString());
            nl.setMaMon(cbxMaMon.getSelectedItem().toString());
            nl.setMaNL(txtMaNL.getText());
            nl.setTenNL(txtTenNL.getText());
            nl.setSoLuong(Integer.parseInt(txtSL.getText()));
            nl.setDVT(txtDVT.getText());
             nl.setDVT(txtGia.getText());

            NguyenLieuDAO nlDao = new NguyenLieuDAO();
            nlDao.update(nl);
            JOptionPane.showMessageDialog(this, "Sửa thông tin nguyên liệu thành công!");
            lamTrong();
            loadData();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnSuaNLActionPerformed

    private void btnXoaNLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNLActionPerformed
        try {
            //Ngược lại thêm bẫy lỗi nếu trùng khoá chính.
            StringBuffer sb = new StringBuffer();
            if (sb.length() > 0) {
                JOptionPane.showMessageDialog(this, sb);
            } else {
                int selected = JOptionPane.showConfirmDialog(this, "Bạn có muốn xoá nguyên liệu này không!", "Thông báo", JOptionPane.YES_NO_OPTION);
                if (selected == JOptionPane.YES_OPTION) {
                    NguyenLieuDAO nlDao = new NguyenLieuDAO();
                    nlDao.delete(txtMaNL.getText());
                    JOptionPane.showMessageDialog(this, "Đã xoá nguyên liệu thành công!");
                    lamTrong();
                    loadData();
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnXoaNLActionPerformed

    private void btnThoatNLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatNLActionPerformed
        btnThoatNL.setToolTipText("Click để thoát chương trình ");
        int selected = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát chương trình không!", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (selected == JOptionPane.YES_NO_OPTION) {
            FormMenu mn = new FormMenu();
            mn.show();
            this.hide();
        }
    }//GEN-LAST:event_btnThoatNLActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        lamTrong();
        blockButton(true);
        txtMaNL.setEnabled(true);
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FormNhaCungCap ncc = new FormNhaCungCap();
        ncc.show();
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormNguyenLieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormNguyenLieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormNguyenLieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormNguyenLieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormNguyenLieu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSuaNL;
    private javax.swing.JButton btnThemNL;
    private javax.swing.JButton btnThoatNL;
    private javax.swing.JButton btnXoaNL;
    private javax.swing.JComboBox<String> cbxMaMon;
    private javax.swing.JComboBox<String> cbxMaNCC;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNguyenLieu;
    private javax.swing.JTextField txtDVT;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMaNL;
    private javax.swing.JTextField txtSL;
    private javax.swing.JTextField txtTenNL;
    // End of variables declaration//GEN-END:variables
}
