/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlycoffee;

import DAO.LoaiDoUongDAO;
import Model.LoaiDoUong;
import DBConnect.DBConnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Admin
 */
public class FormLoaiDU extends javax.swing.JFrame {

    DefaultTableModel tblModelLDU;
    /**
     * Creates new form FormLoaiDU
     */
    public FormLoaiDU() {
        initComponents();
        setLocationRelativeTo(null);
        initTable();
        loadData();
        setTitle("Loại Đồ Uống");
    }

    private void lamTrong() {
        txtMaLoai.setText("");
        txtTenLoai.setText("");
    }

    public boolean blockButton(boolean x) {
        if (x == true) {
            btnSuaLDU.setEnabled(false);
            btnXoaLDU.setEnabled(false);
            btnThemLDU.setEnabled(true);
            btnThoatLDU.setEnabled(true);
            return true;
        } else {
            btnSuaLDU.setEnabled(true);
            btnXoaLDU.setEnabled(true);
            btnThemLDU.setEnabled(false);
            btnThoatLDU.setEnabled(false);
            return false;
        }
    }

    private void initTable() {
        tblModelLDU = new DefaultTableModel();
        tblModelLDU.setColumnIdentifiers(new String[]{"MaLoai", "TenLoai"});
        tblLoaiDoUong.setModel(tblModelLDU);
    }

    public void loadData() {
        try {
            DBConnect a = new DBConnect();
            Connection con = a.getConnection();
            String sql = "Select * from LoaiDoUong";
            PreparedStatement pstmt = con.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            tblModelLDU.setRowCount(0);
            while (rs.next()) {
                String[] row = new String[]{
                    rs.getString("MaLoai"), rs.getString("TenLoai")
                };
                tblModelLDU.addRow(row);
            }
            tblModelLDU.fireTableDataChanged();
            rs.close();
            pstmt.close();
            con.close();
            blockButton(true);
            txtMaLoai.setEnabled(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
            ex.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLoaiDoUong = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaLoai = new javax.swing.JTextField();
        txtTenLoai = new javax.swing.JTextField();
        btnThemLDU = new javax.swing.JButton();
        btnSuaLDU = new javax.swing.JButton();
        btnXoaLDU = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnThoatLDU = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 23)); // NOI18N
        jLabel2.setText("Loại Đồ Uống");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        tblLoaiDoUong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã Loại", "Tên Loại"
            }
        ));
        tblLoaiDoUong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoaiDoUongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLoaiDoUong);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 280, 100));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel1.setText("Mã Loại");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setText("Tên Loại");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));
        getContentPane().add(txtMaLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 80, 30));
        getContentPane().add(txtTenLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 170, 30));

        btnThemLDU.setBackground(new java.awt.Color(255, 255, 204));
        btnThemLDU.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnThemLDU.setText("Thêm");
        btnThemLDU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemLDUActionPerformed(evt);
            }
        });
        getContentPane().add(btnThemLDU, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, 27));

        btnSuaLDU.setBackground(new java.awt.Color(255, 255, 204));
        btnSuaLDU.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnSuaLDU.setText("Sửa");
        btnSuaLDU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaLDUActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuaLDU, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, -1, 27));

        btnXoaLDU.setBackground(new java.awt.Color(255, 255, 204));
        btnXoaLDU.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnXoaLDU.setText("Xoá");
        btnXoaLDU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaLDUActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoaLDU, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, 27));

        btnLamMoi.setBackground(new java.awt.Color(255, 255, 204));
        btnLamMoi.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        getContentPane().add(btnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, 27));

        btnThoatLDU.setBackground(new java.awt.Color(255, 255, 204));
        btnThoatLDU.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnThoatLDU.setText("Thoát");
        btnThoatLDU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatLDUActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoatLDU, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, 27));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/backround.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblLoaiDoUongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoaiDoUongMouseClicked
        int row = tblLoaiDoUong.getSelectedRow();
        txtMaLoai.setEnabled(false);
        blockButton(false);
        if (row >= 0) {
            txtMaLoai.setText(tblLoaiDoUong.getValueAt(row, 0) + "");
            txtTenLoai.setText(tblLoaiDoUong.getValueAt(row, 1) + "");
        }
    }//GEN-LAST:event_tblLoaiDoUongMouseClicked

    private void btnThemLDUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemLDUActionPerformed
        StringBuffer sb = new StringBuffer();
        if (txtMaLoai.getText().equals("") || txtTenLoai.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập đủ thông tin!", "Thông báo!", JOptionPane.ERROR_MESSAGE);
            //Bẫy lỗi nhập thiếu dữ liệu.
        } else {
            if (txtMaLoai.getText().trim().length() > 6) {
                JOptionPane.showMessageDialog(this, "Mã loại đồ uống không vượt quá 6 ký tự! ");
                txtMaLoai.grabFocus();
            }
            //Ngược lại thêm bẫy lỗi nếu trùng khoá chính.

            if (sb.length() > 0) {    //Nếu if trên đúng thì sẽ thêm vào sb 1 đoạn string
                //Kiểm tra độ dài chuỗi này nếu lớn hơn  0 tức là có thông báo
                JOptionPane.showMessageDialog(this, sb);
                return;
            } else {
                try {
                    LoaiDoUong ldu = new LoaiDoUong();
                    ldu.setMaLoai(txtMaLoai.getText());
                    ldu.setTenLoai(txtTenLoai.getText());

                    LoaiDoUongDAO lduDao = new LoaiDoUongDAO();
                    lduDao.insert(ldu);
                    JOptionPane.showMessageDialog(this, "Thêm loại đồ uống thành công!");
                    lamTrong();
                    loadData();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Mã loại đồ uống bị trùng lặp!");
                    ex.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_btnThemLDUActionPerformed

    private void btnSuaLDUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaLDUActionPerformed
        StringBuffer sb = new StringBuffer();
        if (txtMaLoai.getText().equals("") || txtTenLoai.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập đủ thông tin!", "Thông báo!", JOptionPane.ERROR_MESSAGE);
            //Bẫy lỗi nhập thiếu dữ liệu.
        }
        //Ngược lại thêm bẫy lỗi nếu trùng khoá chính.
        if (sb.length() > 0) {    //Nếu if trên đúng thì sẽ thêm vào sb 1 đoạn string
            //Kiểm tra độ dài chuỗi này nếu lớn hơn  0 tức là có thông báo
            JOptionPane.showMessageDialog(this, sb);
            return;
        }
        try {
            LoaiDoUong ldu = new LoaiDoUong();
            ldu.setMaLoai(txtMaLoai.getText());
            ldu.setTenLoai(txtTenLoai.getText());

            LoaiDoUongDAO lduDao = new LoaiDoUongDAO();
            lduDao.update(ldu);
            JOptionPane.showMessageDialog(this, "Sửa thông tin loại đồ uống thành công!");
            lamTrong();
            loadData();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnSuaLDUActionPerformed

    private void btnXoaLDUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaLDUActionPerformed
        try {
            //Ngược lại thêm bẫy lỗi nếu trùng khoá chính.
            StringBuffer sb = new StringBuffer();
            if (sb.length() > 0) {
                JOptionPane.showMessageDialog(this, sb);
            } else {
                int selected = JOptionPane.showConfirmDialog(this, "Bạn có muốn xoá chức vụ này không!", "Thông báo", JOptionPane.YES_NO_OPTION);
                if (selected == JOptionPane.YES_OPTION) {
                    LoaiDoUongDAO lduDao = new LoaiDoUongDAO();
                    lduDao.delete(txtMaLoai.getText());
                    JOptionPane.showMessageDialog(this, "Đã xoá loại đồ uống thành công!");
                    lamTrong();
                    loadData();
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnXoaLDUActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        lamTrong();
        blockButton(true);
        txtMaLoai.setEnabled(true);
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnThoatLDUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatLDUActionPerformed
        btnThoatLDU.setToolTipText("Click để thoát chương trình ");
        int selected = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát chương trình không!", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (selected == JOptionPane.YES_NO_OPTION) {
            FormDoUong mn = new FormDoUong();
            mn.show();
            this.hide();
        }
    }//GEN-LAST:event_btnThoatLDUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLoaiDU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLoaiDU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLoaiDU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLoaiDU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLoaiDU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSuaLDU;
    private javax.swing.JButton btnThemLDU;
    private javax.swing.JButton btnThoatLDU;
    private javax.swing.JButton btnXoaLDU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLoaiDoUong;
    private javax.swing.JTextField txtMaLoai;
    private javax.swing.JTextField txtTenLoai;
    // End of variables declaration//GEN-END:variables
}
