/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlycoffee;

import DAO.ChucVuDAO;
import DBConnect.DBConnect;
import Model.ChucVu;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Admin
 */
public class FormChucVu extends javax.swing.JFrame {

    DefaultTableModel tblModelCV;

    public FormChucVu() {
        initComponents();
        setLocationRelativeTo(null);
        initTable();
        loadData();
        setTitle("Chức Vụ");
    }

    private void lamTrong() {
        txtMaCV.setText("");
        txtTenCV.setText("");
    }

    public boolean blockButton(boolean x) {
        if (x == true) {
            btnSuaCV.setEnabled(false);
            btnXoaCV.setEnabled(false);
            btnThemCV.setEnabled(true);
            btnThoatCV.setEnabled(true);
            return true;
        } else {
            btnSuaCV.setEnabled(true);
            btnXoaCV.setEnabled(true);
            btnThemCV.setEnabled(false);
            btnThoatCV.setEnabled(false);
            return false;
        }
    }

    private void initTable() {
        tblModelCV = new DefaultTableModel();
        tblModelCV.setColumnIdentifiers(new String[]{"MaCV", "TenCV"});
        tblChucVu.setModel(tblModelCV);
    }

    public void loadData() {
        try {
            DBConnect a = new DBConnect();
            Connection con = a.getConnection();
            String sql = "Select * from ChucVu";
            PreparedStatement pstmt = con.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            tblModelCV.setRowCount(0);
            while (rs.next()) {
                String[] row = new String[]{
                    rs.getString("MaCV"), rs.getString("TenCV")
                };
                tblModelCV.addRow(row);
            }
            tblModelCV.fireTableDataChanged();
            rs.close();
            pstmt.close();
            con.close();
            blockButton(true);
            txtMaCV.setEnabled(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaCV = new javax.swing.JTextField();
        txtTenCV = new javax.swing.JTextField();
        btnThemCV = new javax.swing.JButton();
        btnSuaCV = new javax.swing.JButton();
        btnXoaCV = new javax.swing.JButton();
        btnThoatCV = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChucVu = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 23)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/jops.png"))); // NOI18N
        jLabel1.setText("Quản Lý Chức Vụ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel2.setText("Mã Chức Vụ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel3.setText("Tên Chức Vụ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));
        getContentPane().add(txtMaCV, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 50, 130, 30));
        getContentPane().add(txtTenCV, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 130, 30));

        btnThemCV.setBackground(new java.awt.Color(255, 255, 204));
        btnThemCV.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnThemCV.setText("Thêm");
        btnThemCV.setDefaultCapable(false);
        btnThemCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemCVActionPerformed(evt);
            }
        });
        getContentPane().add(btnThemCV, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 260, 80, 30));

        btnSuaCV.setBackground(new java.awt.Color(255, 255, 204));
        btnSuaCV.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnSuaCV.setText("Sửa");
        btnSuaCV.setDefaultCapable(false);
        btnSuaCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaCVActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuaCV, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 70, 30));

        btnXoaCV.setBackground(new java.awt.Color(255, 255, 204));
        btnXoaCV.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnXoaCV.setText("Xoá");
        btnXoaCV.setAutoscrolls(true);
        btnXoaCV.setDefaultCapable(false);
        btnXoaCV.setFocusCycleRoot(true);
        btnXoaCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaCVActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoaCV, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 70, 30));

        btnThoatCV.setBackground(new java.awt.Color(255, 255, 204));
        btnThoatCV.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnThoatCV.setText("Thoát");
        btnThoatCV.setDefaultCapable(false);
        btnThoatCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatCVActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoatCV, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, 30));

        btnLamMoi.setBackground(new java.awt.Color(255, 255, 204));
        btnLamMoi.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        getContentPane().add(btnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, -1, 30));

        tblChucVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã Chức Vụ", "Tên Chức Vụ"
            }
        ));
        tblChucVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblChucVuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblChucVu);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 420, 200));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/backround.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, -150, 810, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblChucVuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblChucVuMouseClicked
        int row = tblChucVu.getSelectedRow();
        txtMaCV.setEnabled(false);
        blockButton(false);
        if (row >= 0) {
            txtMaCV.setText(tblChucVu.getValueAt(row, 0) + "");
            txtTenCV.setText(tblChucVu.getValueAt(row, 1) + "");
        }
        
        
        
    }//GEN-LAST:event_tblChucVuMouseClicked

    private void btnThemCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemCVActionPerformed
        StringBuffer sb = new StringBuffer();
        if (txtMaCV.getText().equals("") || txtTenCV.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập đủ thông tin!", "Thông báo!", JOptionPane.ERROR_MESSAGE);
            //Bẫy lỗi nhập thiếu dữ liệu.
        } else {
            if (txtMaCV.getText().trim().length() > 6) {
                JOptionPane.showMessageDialog(this, "Mã chức vụ không vượt quá 6 ký tự! ");
                txtMaCV.grabFocus();
            }
            //Ngược lại thêm bẫy lỗi nếu trùng khoá chính.

            if (sb.length() > 0) {    //Nếu if trên đúng thì sẽ thêm vào sb 1 đoạn string
                //Kiểm tra độ dài chuỗi này nếu lớn hơn  0 tức là có thông báo
                JOptionPane.showMessageDialog(this, sb);
                return;
            } else {
                try {
                    ChucVu cv = new ChucVu();
                    cv.setMaCV(txtMaCV.getText());
                    cv.setTenCV(txtTenCV.getText());

                    ChucVuDAO cvDao = new ChucVuDAO();
                    cvDao.insert(cv);
                    JOptionPane.showMessageDialog(this, "Thêm chức vụ thành công!");
                    lamTrong();
                    loadData();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Mã chức vụ bị trùng lặp!");
                    ex.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_btnThemCVActionPerformed

    private void btnSuaCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaCVActionPerformed
        StringBuffer sb = new StringBuffer();
        if (txtMaCV.getText().equals("") || txtTenCV.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập đủ thông tin!", "Thông báo!", JOptionPane.ERROR_MESSAGE);
            //Bẫy lỗi nhập thiếu dữ liệu.
        }
        //Ngược lại thêm bẫy lỗi nếu trùng khoá chính.
        if (sb.length() > 0) {    //Nếu if trên đúng thì sẽ thêm vào sb 1 đoạn string
            //Kiểm tra độ dài chuỗi này nếu lớn hơn  0 tức là có thông báo
            JOptionPane.showMessageDialog(this, sb);
            return;
        }
        try {
            ChucVu cv = new ChucVu();
            cv.setMaCV(txtMaCV.getText());
            cv.setTenCV(txtTenCV.getText());

            ChucVuDAO cvDao = new ChucVuDAO();
            cvDao.update(cv);
            JOptionPane.showMessageDialog(this, "Sửa thông tin chức vụ thành công!");
            lamTrong();
            loadData();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnSuaCVActionPerformed

    private void btnXoaCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaCVActionPerformed
        try {
            //Ngược lại thêm bẫy lỗi nếu trùng khoá chính.
            StringBuffer sb = new StringBuffer();
            if (sb.length() > 0) {
                JOptionPane.showMessageDialog(this, sb);
            } else {
                int selected = JOptionPane.showConfirmDialog(this, "Bạn có muốn xoá chức vụ này không!", "Thông báo", JOptionPane.YES_NO_OPTION);
                if (selected == JOptionPane.YES_OPTION) {
                    ChucVuDAO cvDao = new ChucVuDAO();
                    cvDao.delete(txtMaCV.getText());
                    JOptionPane.showMessageDialog(this, "Đã xoá chức vụ thành công!");
                    lamTrong();
                    loadData();
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnXoaCVActionPerformed

    private void btnThoatCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatCVActionPerformed
        btnThoatCV.setToolTipText("Click để thoát chương trình ");
        int selected = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát chương trình không!", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (selected == JOptionPane.YES_NO_OPTION) {
            FormNhanVien mn = new FormNhanVien();
            mn.show();
            this.hide();
        }
    }//GEN-LAST:event_btnThoatCVActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        lamTrong();
        blockButton(true);
        txtMaCV.setEnabled(true);
    }//GEN-LAST:event_btnLamMoiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormChucVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormChucVu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSuaCV;
    private javax.swing.JButton btnThemCV;
    private javax.swing.JButton btnThoatCV;
    private javax.swing.JButton btnXoaCV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tblChucVu;
    private javax.swing.JTextField txtMaCV;
    private javax.swing.JTextField txtTenCV;
    // End of variables declaration//GEN-END:variables
}
