/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlycoffee;

import DBConnect.DBConnect;
import java.beans.Statement;
import java.sql.Connection;
import java.time.Clock;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import quanlycoffee.FormChucVu;
import quanlycoffee.FormNhanVien;
import quanlycoffee.FormNguyenLieu;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.util.Hashtable;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.view.*;
import net.sf.jasperreports.engine.*;

/**
 *
 * @author Admin
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Trang Chủ");

        new Thread() {

            public void run() {

                while (true) {
                    Calendar ca = new GregorianCalendar();
                    int hour = ca.get(Calendar.HOUR);
                    int min = ca.get(Calendar.MINUTE);
                    int sec = ca.get(Calendar.SECOND);
                    int a_pm = ca.get(Calendar.AM_PM);
                    String day_night;
                    if (a_pm == 1) {
                        day_night = "PM";
                    } else {
                        day_night = "AM";
                    }
                    String time = hour + ":" + min + ":" + sec + " " + day_night;
                    Clock.setText(time);
                }
            }
        }.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Clock = new javax.swing.JLabel();
        txtBanHang = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        statusmenu = new javax.swing.JMenu();
        it_logout = new javax.swing.JMenuItem();
        it_exit = new javax.swing.JMenuItem();
        managemenu = new javax.swing.JMenu();
        it_qlnv = new javax.swing.JMenuItem();
        it_qldu = new javax.swing.JMenuItem();
        it_qlnvl = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        Clock.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        Clock.setText("Clock");
        jPanel1.add(Clock);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 140, 30));

        txtBanHang.setBackground(new java.awt.Color(255, 255, 204));
        txtBanHang.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        txtBanHang.setText("Bán Hàng");
        txtBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBanHangActionPerformed(evt);
            }
        });
        getContentPane().add(txtBanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/backround.jpg"))); // NOI18N
        jLabel1.setText("Bán Hàng");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-300, -220, 810, 460));
        setSize(1650,1080);

        statusmenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        statusmenu.setText("Tùy chọn");
        statusmenu.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        statusmenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusmenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        statusmenu.setMargin(new java.awt.Insets(3, 8, 3, 8));
        statusmenu.setMaximumSize(new java.awt.Dimension(70, 32767));

        it_logout.setBackground(new java.awt.Color(255, 255, 204));
        it_logout.setFont(new java.awt.Font("Times New Roman", 2, 15)); // NOI18N
        it_logout.setText("Logout");
        it_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                it_logoutActionPerformed(evt);
            }
        });
        statusmenu.add(it_logout);

        it_exit.setBackground(new java.awt.Color(255, 255, 204));
        it_exit.setFont(new java.awt.Font("Times New Roman", 2, 15)); // NOI18N
        it_exit.setText("Exit");
        it_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                it_exitActionPerformed(evt);
            }
        });
        statusmenu.add(it_exit);

        jMenuBar1.add(statusmenu);

        managemenu.setBackground(new java.awt.Color(255, 255, 204));
        managemenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        managemenu.setText("Quản lí");
        managemenu.setAlignmentX(1.0F);
        managemenu.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        managemenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        managemenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        managemenu.setMargin(new java.awt.Insets(3, 8, 3, 8));
        managemenu.setMaximumSize(new java.awt.Dimension(65, 32767));

        it_qlnv.setBackground(new java.awt.Color(255, 255, 204));
        it_qlnv.setFont(new java.awt.Font("Times New Roman", 2, 15)); // NOI18N
        it_qlnv.setText("Nhân viên");
        it_qlnv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                it_qlnvActionPerformed(evt);
            }
        });
        managemenu.add(it_qlnv);

        it_qldu.setBackground(new java.awt.Color(255, 255, 204));
        it_qldu.setFont(new java.awt.Font("Times New Roman", 2, 15)); // NOI18N
        it_qldu.setText("Đồ uống");
        it_qldu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                it_qlduActionPerformed(evt);
            }
        });
        managemenu.add(it_qldu);

        it_qlnvl.setBackground(new java.awt.Color(255, 255, 204));
        it_qlnvl.setFont(new java.awt.Font("Times New Roman", 2, 15)); // NOI18N
        it_qlnvl.setText("Nguyên vật liệu");
        it_qlnvl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                it_qlnvlActionPerformed(evt);
            }
        });
        managemenu.add(it_qlnvl);

        jMenuBar1.add(managemenu);

        jMenu1.setBackground(new java.awt.Color(255, 255, 204));
        jMenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenu1.setText("Thống Kê");
        jMenu1.setAlignmentX(1.0F);
        jMenu1.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        jMenuItem2.setBackground(new java.awt.Color(255, 255, 204));
        jMenuItem2.setFont(new java.awt.Font("Times New Roman", 2, 15)); // NOI18N
        jMenuItem2.setText("Thống Kê");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setBackground(new java.awt.Color(255, 255, 204));
        jMenuItem3.setFont(new java.awt.Font("Times New Roman", 2, 15)); // NOI18N
        jMenuItem3.setText("Report");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void it_qlnvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_it_qlnvActionPerformed
        FormNhanVien nv = new FormNhanVien();
        nv.show();
        this.hide();
    }//GEN-LAST:event_it_qlnvActionPerformed

    private void it_qlduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_it_qlduActionPerformed
        FormDoUong du = new FormDoUong();
        du.show();
        this.hide();
    }//GEN-LAST:event_it_qlduActionPerformed

    private void it_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_it_logoutActionPerformed
        int selected = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát chương trình không!", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (selected == JOptionPane.YES_NO_OPTION) {
            FormDangNhap dn = new FormDangNhap();
            dn.show();
            this.hide();
        }
    }//GEN-LAST:event_it_logoutActionPerformed

    private void it_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_it_exitActionPerformed
        int selected = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát chương trình không!", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (selected == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_it_exitActionPerformed

    private void it_qlnvlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_it_qlnvlActionPerformed
        FormNguyenLieu nl = new FormNguyenLieu();
        nl.show();
        this.hide();
    }//GEN-LAST:event_it_qlnvlActionPerformed

    private void txtBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBanHangActionPerformed
        FormBanHang bh = new FormBanHang();
        bh.show();
        this.hide();
    }//GEN-LAST:event_txtBanHangActionPerformed


    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        XuatHoaDon();       
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    private void XuatHoaDon(){
        //Khai bao duong dan den file report
        String link = "C:\\Users\\ADMIN\\OneDrive\\Documents\\NetBeansProjects\\QuanLyCoffee\\src\\quanlycoffee\\report1.jrxml";
        Connection conn = null;
        Statement st = null;
        ResultSet rs = null;
        try {
            //Tạo kết nối đến SQL
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=QuanLyCafe;user=sa;password=123456;encrypt=true;trustServerCertificate=true;");

            // tạo JasperReport
            JasperReport jr = JasperCompileManager.compileReport(link);
//tạo JasperPrint
            JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
//Tạo JasperViewer
            JasperViewer.viewReport(jp);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked

    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FormThongKe tk = new FormThongKe();
        tk.show();
        this.hide();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * FromChucVu
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMenu().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Clock;
    private javax.swing.JMenuItem it_exit;
    private javax.swing.JMenuItem it_logout;
    private javax.swing.JMenuItem it_qldu;
    private javax.swing.JMenuItem it_qlnv;
    private javax.swing.JMenuItem it_qlnvl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu managemenu;
    private javax.swing.JMenu statusmenu;
    private javax.swing.JButton txtBanHang;
    // End of variables declaration//GEN-END:variables
}
