/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlycoffee;

import DAO.DoUongDAO;
import DBConnect.DBConnect;
import Model.DoUong;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class FormDoUong extends javax.swing.JFrame {

    DefaultTableModel tblModelDU;

    /**
     * Creates new form FormDoUong
     */
    public FormDoUong() {
        initComponents();
        setLocationRelativeTo(null);
        initTable();
        loadData();
        loadCombobox();
        setTitle("Đồ Uống");
    }

    private void lamTrong() {
        txtMaMon.setText(null);
        cbxMaLoai.setSelectedItem(null);
        txtTenMon.setText("");
        txtGiaMon.setText("");
    }

    public boolean blockButton(boolean x) {
        if (x == true) {
            btnSuaDU.setEnabled(false);
            btnXoaDU.setEnabled(false);
            btnThemDU.setEnabled(true);
            btnThoatDU.setEnabled(true);
            return true;
        } else {
            btnSuaDU.setEnabled(true);
            btnXoaDU.setEnabled(true);
            btnThemDU.setEnabled(false);
            btnThoatDU.setEnabled(false);
            return false;
        }
    }

    public void loadCombobox() {
        try {
            DBConnect a = new DBConnect();
            Connection con = a.getConnection();
            PreparedStatement psMaLoai = con.prepareStatement("Select MaLoai from LoaiDoUong group by MaLoai");
            ResultSet rsMaLoai = psMaLoai.executeQuery();
            while (rsMaLoai.next()) {
                cbxMaLoai.addItem(rsMaLoai.getString("MaLoai"));
            }
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }

    private void initTable() {
        tblModelDU = new DefaultTableModel();
        tblModelDU.setColumnIdentifiers(new String[]{"MaLoai", "MaMon", "TenMon", "Gia"});
        tblDoUong.setModel(tblModelDU);
    }

    public void loadData() {
        try {
            DBConnect a = new DBConnect();
            Connection con = a.getConnection();
            String sql = "Select * from DoUong ";
            PreparedStatement pstmt = con.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            tblModelDU.setRowCount(0);
            while (rs.next()) {
                String[] row = new String[]{
                    rs.getString("MaLoai"), rs.getString("MaMon"), rs.getString("TenMon"), rs.getString("Gia")
                };
                tblModelDU.addRow(row);
            }
            tblModelDU.fireTableDataChanged();
            rs.close();
            pstmt.close();
            con.close();
            blockButton(true);
            txtMaMon.setEnabled(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
            ex.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnThemDU = new javax.swing.JButton();
        btnSuaDU = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnXoaDU = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDoUong = new javax.swing.JTable();
        txtMaMon = new javax.swing.JTextField();
        cbxMaLoai = new javax.swing.JComboBox<>();
        txtGiaMon = new javax.swing.JTextField();
        txtTenMon = new javax.swing.JTextField();
        btnLamMoi = new javax.swing.JButton();
        btnThoatDU = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnThemDU.setBackground(new java.awt.Color(255, 255, 204));
        btnThemDU.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnThemDU.setText("Thêm");
        btnThemDU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDUActionPerformed(evt);
            }
        });
        getContentPane().add(btnThemDU, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, 30));

        btnSuaDU.setBackground(new java.awt.Color(255, 255, 204));
        btnSuaDU.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnSuaDU.setText("Sửa");
        btnSuaDU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaDUActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuaDU, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, -1, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 23)); // NOI18N
        jLabel1.setText("Quản Lý Đồ Uống");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel2.setText("Mã Món");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel3.setText("Mã Loại");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, 30));

        btnXoaDU.setBackground(new java.awt.Color(255, 255, 204));
        btnXoaDU.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnXoaDU.setText("Xoá");
        btnXoaDU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaDUActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoaDU, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, -1, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel4.setText("Tên Món");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel5.setText("Giá");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, -1, 30));

        tblDoUong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Loại", "Mã Món", "Tên Món", "Giá "
            }
        ));
        tblDoUong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDoUongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDoUong);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 510, 210));
        getContentPane().add(txtMaMon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 130, 30));
        getContentPane().add(cbxMaLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 100, 30));
        getContentPane().add(txtGiaMon, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 160, 30));
        getContentPane().add(txtTenMon, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 200, 30));

        btnLamMoi.setBackground(new java.awt.Color(255, 255, 204));
        btnLamMoi.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        getContentPane().add(btnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, -1, 30));

        btnThoatDU.setBackground(new java.awt.Color(255, 255, 204));
        btnThoatDU.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnThoatDU.setText("Thoát");
        btnThoatDU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatDUActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoatDU, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, -1, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jButton1.setText("LoaiDoUong");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, -1, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/backround.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -120, -1, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDoUongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDoUongMouseClicked
        int row = tblDoUong.getSelectedRow();
        txtMaMon.setEnabled(false);
        blockButton(false);
        if (row >= 0) {
            cbxMaLoai.setSelectedItem(tblDoUong.getModel().getValueAt(row, 0) + "");
            txtMaMon.setText(tblDoUong.getValueAt(row, 1) + "");
            txtTenMon.setText(tblDoUong.getValueAt(row, 2) + "");
            txtGiaMon.setText(tblDoUong.getValueAt(row, 3) + "");
        }
    }//GEN-LAST:event_tblDoUongMouseClicked

    private void btnThemDUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDUActionPerformed
        StringBuffer sb = new StringBuffer();
        if (txtMaMon.getText().equals("") || txtTenMon.getText().equals("") || txtGiaMon.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập đủ thông tin!", "Thông báo!", JOptionPane.ERROR_MESSAGE);
            //Bẫy lỗi nhập thiếu dữ liệu.
        } else {
            if (txtMaMon.getText().trim().length() > 6) {
                JOptionPane.showMessageDialog(this, "Mã món không vượt quá 6 ký tự! ");
                txtMaMon.grabFocus();
            }
            if (sb.length() > 0) {    //Nếu if trên đúng thì sẽ thêm vào sb 1 đoạn string
                //Kiểm tra độ dài chuỗi này nếu lớn hơn  0 tức là có thông báo
                JOptionPane.showMessageDialog(this, sb);
                return;
            } else {
                try {
                    DoUong du = new DoUong();
                    du.setMaLoai(cbxMaLoai.getSelectedItem().toString());
                    du.setMaMon(txtMaMon.getText());
                    du.setTenMon(txtTenMon.getText());
                    du.setGia(txtGiaMon.getText());

                    DoUongDAO duDao = new DoUongDAO();
                    duDao.insert(du);
                    JOptionPane.showMessageDialog(this, "Thêm món thành công!");
                    lamTrong();
                    loadData();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Mã món trùng lặp!");
                    ex.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_btnThemDUActionPerformed

    private void btnSuaDUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaDUActionPerformed
        StringBuffer sb = new StringBuffer();
       if (txtMaMon.getText().equals("") || txtTenMon.getText().equals("") || txtGiaMon.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập đủ thông tin!", "Thông báo!", JOptionPane.ERROR_MESSAGE);
            //Bẫy lỗi nhập thiếu dữ liệu.
        }
        //Ngược lại thêm bẫy lỗi nếu trùng khoá chính.
        if (sb.length() > 0) {    //Nếu if trên đúng thì sẽ thêm vào sb 1 đoạn string
            //Kiểm tra độ dài chuỗi này nếu lớn hơn  0 tức là có thông báo
            JOptionPane.showMessageDialog(this, sb);
            return;
        }
        try {
            DoUong du = new DoUong();
                    du.setMaLoai(cbxMaLoai.getSelectedItem().toString());
                    du.setMaMon(txtMaMon.getText());
                    du.setTenMon(txtTenMon.getText());
                    du.setGia(txtGiaMon.getText());

                    DoUongDAO duDao = new DoUongDAO();
                    duDao.update(du);
            JOptionPane.showMessageDialog(this, "Sửa thông tin món thành công!");
            lamTrong();
            loadData();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnSuaDUActionPerformed

    private void btnXoaDUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaDUActionPerformed
        try {
            //Ngược lại thêm bẫy lỗi nếu trùng khoá chính.
            StringBuffer sb = new StringBuffer();
            if (sb.length() > 0) {
                JOptionPane.showMessageDialog(this, sb);
            } else {
                int selected = JOptionPane.showConfirmDialog(this, "Bạn có muốn xoá món này không!", "Thông báo", JOptionPane.YES_NO_OPTION);
                if (selected == JOptionPane.YES_OPTION) {
                    DoUongDAO duDao = new DoUongDAO();
                    duDao.delete(txtMaMon.getText());
                    JOptionPane.showMessageDialog(this, "Đã xoá món thành công!");
                    lamTrong();
                    loadData();
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnXoaDUActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        lamTrong();
        blockButton(true);
        txtMaMon.setEnabled(true);
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnThoatDUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatDUActionPerformed
        btnThoatDU.setToolTipText("Click để thoát chương trình ");
        int selected = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát chương trình không!", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (selected == JOptionPane.YES_NO_OPTION) {
            FormMenu mn = new FormMenu();
            mn.show();
            this.hide();
        }
    }//GEN-LAST:event_btnThoatDUActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         FormLoaiDU ldu = new FormLoaiDU();
            ldu.show();
            this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDoUong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDoUong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDoUong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDoUong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDoUong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSuaDU;
    private javax.swing.JButton btnThemDU;
    private javax.swing.JButton btnThoatDU;
    private javax.swing.JButton btnXoaDU;
    private javax.swing.JComboBox<String> cbxMaLoai;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDoUong;
    private javax.swing.JTextField txtGiaMon;
    private javax.swing.JTextField txtMaMon;
    private javax.swing.JTextField txtTenMon;
    // End of variables declaration//GEN-END:variables
}
