/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlycoffee;

import DAO.NhanVienDAO;
import DBConnect.DBConnect;
import Model.NhanVien;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

public class FormNhanVien extends javax.swing.JFrame {

    DefaultTableModel tblModelNV;

    public FormNhanVien() {
        initComponents();
        setLocationRelativeTo(null);
        initTable();
        loadData();
        loadComboBox();
        blockButton(true);
        setTitle("Nhân Viên");
    }

    private void lamTrong() {
        txtMaNV.setText("");
        cbxChucVu.setSelectedItem(null);
        txtTenNV.setText("");
        rbtNam.setSelected(false);
        rbtNu.setSelected(false);
        txtSDTNV.setText("");
    }

    public boolean blockButton(boolean x){
        if(x == true){
            btnSuaNV.setEnabled(false);
            btnXoaNV.setEnabled(false);
            btnThemNV.setEnabled(true);
            btnThoatNV.setEnabled(true);
            return true;
        }else{
            btnSuaNV.setEnabled(true);
            btnXoaNV.setEnabled(true);
            btnThemNV.setEnabled(false);
            btnThoatNV.setEnabled(false);
            return false;
        }
    }
    
    public void loadComboBox() {
        try {
            DBConnect a = new DBConnect();
            Connection con = a.getConnection();
            PreparedStatement ps = con.prepareStatement("Select MaCV from ChucVu group by MaCV");
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                cbxChucVu.addItem(rs.getString("MaCV"));
            }
        } catch (Exception ex) {
            System.out.println(ex.toString());
        }
    }

    private void initTable() {
        tblModelNV = new DefaultTableModel();
        tblModelNV.setColumnIdentifiers(new String[]{"MaNV", "MaCV", "TenNV", "GT", "SDT"});
        tblNhanVien.setModel(tblModelNV);
    }

    public void loadData() {
        try {
            DBConnect a = new DBConnect();
            Connection con = a.getConnection();
            String sql = "Select * from NhanVien";
            PreparedStatement pstmt = con.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            tblModelNV.setRowCount(0);
            while (rs.next()) {
                String[] row = new String[]{
                    rs.getString("MaNV"), rs.getString("MaCV"), rs.getString("TenNV"), rs.getString("GT"), rs.getString("SDT")
                };
                tblModelNV.addRow(row);
            }
            tblModelNV.fireTableDataChanged();
            rs.close();
            pstmt.close();
            con.close();
            blockButton(true);
            txtMaNV.setEnabled(true);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.toString());
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupGTNV = new javax.swing.ButtonGroup();
        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbxChucVu = new javax.swing.JComboBox<>();
        txtTenNV = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rbtNam = new javax.swing.JRadioButton();
        rbtNu = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtSDTNV = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        btnThemNV = new javax.swing.JButton();
        btnXoaNV = new javax.swing.JButton();
        btnSuaNV = new javax.swing.JButton();
        btnThoatNV = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 23)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/manager.png"))); // NOI18N
        jLabel1.setText("QUẢN LÝ NHÂN VIÊN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, 40));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel2.setText("Mã nhân viên");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        txtMaNV.setAlignmentX(0.4F);
        txtMaNV.setAlignmentY(0.4F);
        getContentPane().add(txtMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 60, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel3.setText("Chức vụ");
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel4.setText("Tên nhân viên");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        cbxChucVu.setToolTipText("");
        cbxChucVu.setAlignmentX(0.4F);
        cbxChucVu.setAlignmentY(0.4F);
        getContentPane().add(cbxChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 90, -1));

        txtTenNV.setAlignmentX(0.4F);
        txtTenNV.setAlignmentY(0.4F);
        getContentPane().add(txtTenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 220, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel5.setText("Giới Tính");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        btnGroupGTNV.add(rbtNam);
        rbtNam.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        rbtNam.setText("Nam");
        getContentPane().add(rbtNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 71, 20));

        btnGroupGTNV.add(rbtNu);
        rbtNu.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        rbtNu.setText("Nữ");
        getContentPane().add(rbtNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 50, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel6.setText("Số Điện Thoại");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, 20));

        txtSDTNV.setAlignmentX(0.4F);
        txtSDTNV.setAlignmentY(0.4F);
        getContentPane().add(txtSDTNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 220, 30));

        tblNhanVien.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Mã CV", "Tên Nhân Viên", "GT", "SĐT"
            }
        ));
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanVien);
        if (tblNhanVien.getColumnModel().getColumnCount() > 0) {
            tblNhanVien.getColumnModel().getColumn(0).setResizable(false);
            tblNhanVien.getColumnModel().getColumn(0).setPreferredWidth(45);
            tblNhanVien.getColumnModel().getColumn(0).setHeaderValue("Mã NV");
            tblNhanVien.getColumnModel().getColumn(1).setResizable(false);
            tblNhanVien.getColumnModel().getColumn(1).setPreferredWidth(45);
            tblNhanVien.getColumnModel().getColumn(1).setHeaderValue("Mã CV");
            tblNhanVien.getColumnModel().getColumn(2).setHeaderValue("Tên Nhân Viên");
            tblNhanVien.getColumnModel().getColumn(3).setResizable(false);
            tblNhanVien.getColumnModel().getColumn(3).setPreferredWidth(45);
            tblNhanVien.getColumnModel().getColumn(3).setHeaderValue("GT");
            tblNhanVien.getColumnModel().getColumn(4).setHeaderValue("SĐT");
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 680, 190));

        btnThemNV.setBackground(new java.awt.Color(255, 255, 204));
        btnThemNV.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnThemNV.setText("Thêm");
        btnThemNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNVActionPerformed(evt);
            }
        });
        getContentPane().add(btnThemNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 70, 30));

        btnXoaNV.setBackground(new java.awt.Color(255, 255, 204));
        btnXoaNV.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnXoaNV.setText("Xoá");
        btnXoaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNVActionPerformed(evt);
            }
        });
        getContentPane().add(btnXoaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 70, 30));

        btnSuaNV.setBackground(new java.awt.Color(255, 255, 204));
        btnSuaNV.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnSuaNV.setText("Sửa");
        btnSuaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaNVActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 70, 30));

        btnThoatNV.setBackground(new java.awt.Color(255, 255, 204));
        btnThoatNV.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnThoatNV.setText("Thoát");
        btnThoatNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatNVActionPerformed(evt);
            }
        });
        getContentPane().add(btnThoatNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 90, 30));

        btnLamMoi.setBackground(new java.awt.Color(255, 255, 204));
        btnLamMoi.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });
        getContentPane().add(btnLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jButton1.setText("QL CV");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 90, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/backround.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, -1, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNVActionPerformed
        StringBuffer sb = new StringBuffer();
        if (txtMaNV.getText().equals("") || txtTenNV.getText().equals("") || txtSDTNV.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập đủ thông tin!", "Thông báo!", JOptionPane.ERROR_MESSAGE);
            //Bẫy lỗi nhập thiếu dữ liệu.
        } else {
            if(txtMaNV.getText().trim().length() > 6){
                JOptionPane.showMessageDialog(this, "Mã nhân viên không vượt quá 6 ký tự! ");
                txtMaNV.grabFocus();
            }
            if (txtSDTNV.getText().trim().length() > 11 || txtSDTNV.getText().trim().length() < 10) {
                JOptionPane.showMessageDialog(this, "Số điện thoại gồm 10-11 số! ");
                txtSDTNV.grabFocus();
                return;
            } else if (!txtSDTNV.getText().trim().matches("0[1-9]{1}\\d{8,9}")) {
                JOptionPane.showMessageDialog(this, "Không đúng định dạng số điện thoại !");
                txtSDTNV.grabFocus();
                return;
            }
            //Ngược lại thêm bẫy lỗi nếu trùng khoá chính.

            if (sb.length() > 0) {    //Nếu if trên đúng thì sẽ thêm vào sb 1 đoạn string
                //Kiểm tra độ dài chuỗi này nếu lớn hơn  0 tức là có thông báo
                JOptionPane.showMessageDialog(this, sb);
                return;
            } else {
                try {
                    NhanVien nv = new NhanVien();
                    nv.setMaNV(txtMaNV.getText());
                    nv.setMaCV(cbxChucVu.getSelectedItem().toString());
                    nv.setTenNV(txtTenNV.getText());
                    nv.setSDT(txtSDTNV.getText());
                    nv.setGT((byte) (rbtNam.isSelected() ? 1 : 0));

                    NhanVienDAO nvDao = new NhanVienDAO();
                    nvDao.insert(nv);
                    JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công!");
                    lamTrong();
                    loadData();
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Mã nhân viên bị trùng lặp!");
                    ex.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_btnThemNVActionPerformed

    private void btnSuaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaNVActionPerformed
        StringBuffer sb = new StringBuffer();
        if (txtMaNV.getText().equals("") || txtTenNV.getText().equals("") || txtSDTNV.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập đủ thông tin!", "Thông báo!", JOptionPane.ERROR_MESSAGE);
            //Bẫy lỗi nhập thiếu dữ liệu.
        }
        //Ngược lại thêm bẫy lỗi nếu trùng khoá chính.
        if (sb.length() > 0) {    //Nếu if trên đúng thì sẽ thêm vào sb 1 đoạn string
            //Kiểm tra độ dài chuỗi này nếu lớn hơn  0 tức là có thông báo
            JOptionPane.showMessageDialog(this, sb);
            return;
        }
        if (txtSDTNV.getText().trim().length() > 11 || txtSDTNV.getText().trim().length() < 10) {
                JOptionPane.showMessageDialog(this, "Số điện thoại gồm 10-11 số! ");
                txtSDTNV.grabFocus();
                return;
            } else if (!txtSDTNV.getText().trim().matches("0[1-9]{1}\\d{8,9}")) {
                JOptionPane.showMessageDialog(this, "Không đúng định dạng số điện thoại !");
                txtSDTNV.grabFocus();
                return;
            }
        try {
            NhanVien nv = new NhanVien();
            nv.setMaNV(txtMaNV.getText());
            nv.setMaCV(cbxChucVu.getSelectedItem().toString());
            nv.setTenNV(txtTenNV.getText());
            nv.setSDT(txtSDTNV.getText());
            nv.setGT((byte) (rbtNam.isSelected() ? 1 : 0));

            NhanVienDAO nvDao = new NhanVienDAO();
            nvDao.update(nv);
            JOptionPane.showMessageDialog(this, "Sửa thông tin nhân viên thành công!");
            lamTrong();
            loadData();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnSuaNVActionPerformed

    private void btnXoaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNVActionPerformed
        try {
            //Ngược lại thêm bẫy lỗi nếu trùng khoá chính.
            StringBuffer sb = new StringBuffer();
            if (sb.length() > 0) {
                JOptionPane.showMessageDialog(this, sb);
            } else {
                int selected = JOptionPane.showConfirmDialog(this, "Bạn có muốn xoá nhân viên này không!", "Thông báo", JOptionPane.YES_NO_OPTION);
                if (selected == JOptionPane.YES_OPTION) {
                    NhanVienDAO nvDao = new NhanVienDAO();
                    nvDao.delete(txtMaNV.getText());
                    JOptionPane.showMessageDialog(this, "Đã xoá nhân viên thành công!");
                    lamTrong();
                    loadData();
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnXoaNVActionPerformed

    private void btnThoatNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatNVActionPerformed
        btnThoatNV.setToolTipText("Click để thoát chương trình ");
        int selected = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát chương trình không!", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (selected == JOptionPane.YES_NO_OPTION) {
            FormMenu mn = new FormMenu();
            mn.show();
            this.dispose();
        }
    }//GEN-LAST:event_btnThoatNVActionPerformed

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        int row = tblNhanVien.getSelectedRow();
        txtMaNV.setEnabled(false);
        blockButton(false);
        if (row >= 0) {
            txtMaNV.setText(tblNhanVien.getValueAt(row, 0) + "");
            cbxChucVu.setSelectedItem(tblNhanVien.getModel().getValueAt(row, 1) + "");
            txtTenNV.setText(tblNhanVien.getValueAt(row, 2) + "");
            if (tblNhanVien.getValueAt(row, 3).toString().equals("1")) {
                rbtNam.setSelected(true);
                rbtNu.setSelected(false);
            } else {
                rbtNam.setSelected(false);
                rbtNu.setSelected(true);
            }
            txtSDTNV.setText(tblNhanVien.getValueAt(row, 4) + "");
        }
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        lamTrong();
        blockButton(true);
        txtMaNV.setEnabled(true);
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FormChucVu cv = new FormChucVu();
        cv.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormNhanVien.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormNhanVien.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormNhanVien.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormNhanVien.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupGTNV;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSuaNV;
    private javax.swing.JButton btnThemNV;
    private javax.swing.JButton btnThoatNV;
    private javax.swing.JButton btnXoaNV;
    private javax.swing.JComboBox<String> cbxChucVu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtNam;
    private javax.swing.JRadioButton rbtNu;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtSDTNV;
    private javax.swing.JTextField txtTenNV;
    // End of variables declaration//GEN-END:variables
}
